_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 41
                - 48
                - 53
                - 55
            "2":
                - 1
                - 41
                - 48
                - 53
                - 55
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
criterion:
    value: MaskedMSELoss
model:
    value: UNet
num_epochs:
    value: 250
optimizer:
    value: Adam
